export default {
    busDescription: "Vitória conta com ônibus panorâmico de turismo, que possui a parte superior aberta para os passageiros terem uma visão privilegiada e ampla da cidade. O serviço de city tour ocorre às quartas-feiras, sábados, domingos e feriados e percorre vários atrativos. O veículo tem 49 lugares disponíveis, inclusive para idosos, gestantes e pessoas com mobilidade reduzida.",
    busTitle: "Bustour Vitória e Vila Velha",
    busLink: "https://www.capixabaturismo.com.br/bustour/",
    busButtonText: "Official website",
    gifts_text: "<p>Seu amor, risos e companhia é tudo o que podemos desejar em nosso dia especial.</p><p>&nbsp;No entanto, se você deseja nos homenagear com um presente, criamos este link abaixo, onde você pode doar ao nosso \"cofrinho\". &nbsp;De fato, é mais prático, pois não será possível trazer de volta nenhum item material no avião.</p><p>&nbsp;Por favor, não se sinta obrigado a participar.</p>",
    greeting: 'Opa pessoal !',
    our_story: 'Nossa historia',
    our_story_content: "<p>Auri e Thiago fizeram contato pela primeira vez em um aplicativo de namoro.</p><p><br></p><p>Vejo você... você está pensando \"De jeito nenhum, um casal tão perfeito e é assim que eles se conheceram?\"! Até supermodelos estão em aplicativos de namoro.</p><p><br></p><p>Começamos rapidamente a conversar e isso levou a intermináveis conversas hilárias no whatsapp (porque, como você sabe, também somos hilários).</p><p><br></p><p>Compartilhando o mesmo amor por bons sarcasmos e as mesmas expectativas de vida, decidimos nos encontrar.</p><p><br></p><p>Quando Auri viu Thiago ela pensou, com uma leve decepção, que ele parecia muito mais velho do que o que ele fingia. Além disso, ele tinha cabelos brancos muito longos que pareciam bastante sedosos, mas não estava combinando com suas fotos. Ela rapidamente ficou aliviada quando percebeu que ele era na verdade o outro cara atrás.</p><p><br></p><p>Mesmo que Thiago gostasse de em dançar um carnaval e cocos e a Auri curtisse queijo e tacar fogo em carros durante as greves francesas, começamos a conversar e encontramos uma forte conexão imediatamente.</p><p><br></p><p>Sabíamos que era o começo de algo para durar.</p><p><br></p><p>Em poucas semanas, eles já tinham conhecido suas incríveis famílias em chamadas de vídeo e um mês depois, Thiago já estava pedindo para Auri morar em conjunto, especialmente porque ele ama lasanha da Auri.</p><p><br></p><p>Quase 6 meses depois, estávamos nos mudando juntos. Estávamos ainda mais convencidos sobre nossas pequenisses e fizemos cada vez mais projetos. Claro, não me engana, às vezes discutimos. Como quando Thiago diz a Auri que Felipe é mais engraçado que ela e que ela é apenas o número 2, ou como quando Auri coloca o dedo no umbigo de Thiago.</p><p><br></p><p>Desde o primeiro dia sabíamos que não era só um romance, mas a melhor amizade de todos os tempos. Só não é assim quando um de nós assiste uma série da Netflix sem o outro ou se Thiago come todo o queijo na geladeira. Mas ninguém é perfeito, certo?</p><p><br></p><p>Quase dois anos depois, Thiago propos a Auri em casamento no Brasil cercado por nossas duas famílias (estávamos sentindo falta do pai de Auri).</p><p><br></p><p>Estamos tão ansiosos para começar este novo capítulo juntos, e mal podemos esperar para comemorar com todas as nossas pessoas favoritas</p><p><br></p>"
}